# Open a PR in flow-go when a PR in cadence is merged
# The PR in flow-go is based on the last opened `auto-cadence-upgrade/*` if it exists, otherwise on the master branch
name: Sync flow-go

# Only run on pull requests merged to master
on:
  pull_request:
    branches:
      - master
    types: [closed]
    paths-ignore:
      - '.github/**'
      - 'compat/**'
      - 'docs/**'
      - 'npm-packages/**'
      - 'rfcs/**'
      - 'tools/**'

jobs:
  sync-flow-go:
    runs-on: ubuntu-latest
    # the PR could have been closed otherwise. Only run if it has actually ben merged
    if: github.event.pull_request.merged == true
    steps:
    
      # checkout the repo we are going to be updating with fetch depth of 0 to get all the branches for the next step
      - name: Checkout onflow/flow-go
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.REMOTE_REPO_PAT }}
          repository: onflow/flow-go
      
      # get the latest update branch name to base the PR on that branch
      - name: Get onflow/flow-go base branch name
        run: |
          git fetch
          BRANCH=$(git branch -r -l "*auto-cadence-upgrade/*" --format "%(refname:lstrip=3)" | sort -r | head -n 1)
          [ -z $BRANCH ] && BRANCH=master
          echo "BASE_BRANCH=$BRANCH" >> $GITHUB_ENV

      # create new branch name
      - name: Create new branch name
        run: |
          NEW_BRANCH=auto-cadence-upgrade/$( date +%s )/${{ github.event.pull_request.head.ref }}
          echo "NEW_BRANCH=$NEW_BRANCH" >> $GITHUB_ENV

      # checkout the correct branch of the remote repo
      - name: Checkout onflow/flow-go branch
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REMOTE_REPO_PAT }}
          repository: onflow/flow-go
          ref: ${{ env.BASE_BRANCH }}

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.x'

      - name: Update Cadence
        run: |
          go get github.com/onflow/cadence@${{ github.event.pull_request.merge_commit_sha }}
          cd integration
          go get github.com/onflow/cadence@${{ github.event.pull_request.merge_commit_sha }}
          cd ..
      
      - name: go mod tidy
        run: |
          go mod tidy
          cd integration
          go mod tidy
          cd ..

      # create the pull request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.REMOTE_REPO_PAT }}
          commit-message: update Cadence to commit ${{ github.event.pull_request.merge_commit_sha }}
          title: "Auto Cadence Update: ${{ github.event.pull_request.title }}"
          body: |
              Auto generated PR to update Cadence version.

              References: ${{ github.event.pull_request.html_url }}
          branch: ${{ env.NEW_BRANCH }}
          delete-branch: true

          # we can tweak the following:
          # labels: A comma or newline-separated list of labels.
          # assignees: A comma or newline-separated list of assignees (GitHub usernames).
          # reviewers: A comma or newline-separated list of reviewers (GitHub usernames) to request a review from.
          assignees: janezpodhostnik,ramtinms,turbolent,SupunS